/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.hardcodeando.ui;

import ar.com.hardcodeando.ui.utils.OperacionMd5Dialog;
import ar.com.hardcodeando.ui.utils.Ronda4Dialog;
import ar.com.hardcodeando.ui.utils.Ronda3Dialog;
import ar.com.hardcodeando.ui.utils.Ronda2Dialog;
import ar.com.hardcodeando.ui.utils.Ronda1Dialog;
import ar.com.hardcodeando.algorithm.MD5;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author estefi
 */
public class MD5PanelEvaluar extends javax.swing.JPanel {

    /**
     * Creates new form MD5Panel
     */
    public MD5PanelEvaluar() {
        initComponents();
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jTabbedPane1.setEnabledAt(4, false);
        jTabbedPane1.setEnabledAt(5, false);
        jTabbedPane1.setEnabledAt(6, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        IntroMD5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelPaso1 = new javax.swing.JPanel();
        lblHeaderPaso3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textMensaje = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel80 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        panelPaso2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelPaso3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        panelPaso4i = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        panelPaso4ii = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        sumaFinal = new javax.swing.JLabel();
        ronda1fila2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        ronda1fila1 = new javax.swing.JLabel();
        ronda1fila4 = new javax.swing.JLabel();
        ronda1fila3 = new javax.swing.JLabel();
        ronda1fila5 = new javax.swing.JLabel();
        ronda1fila6 = new javax.swing.JLabel();
        ronda1fila7 = new javax.swing.JLabel();
        ronda1fila8 = new javax.swing.JLabel();
        ronda1fila9 = new javax.swing.JLabel();
        ronda1fila10 = new javax.swing.JLabel();
        ronda1fila11 = new javax.swing.JLabel();
        ronda1fila12 = new javax.swing.JLabel();
        ronda1fila13 = new javax.swing.JLabel();
        ronda1fila14 = new javax.swing.JLabel();
        ronda1fila15 = new javax.swing.JLabel();
        ronda1fila16 = new javax.swing.JLabel();
        valoresIniciales = new javax.swing.JLabel();
        panelPaso5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        hashSalida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1024, 1000));
        setLayout(null);

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(846, 519));

        IntroMD5.setMinimumSize(new java.awt.Dimension(0, 0));
        IntroMD5.setPreferredSize(new java.awt.Dimension(80, 379));
        IntroMD5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Comenzar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        IntroMD5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Introducción");
        IntroMD5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel12.setText("<html>MD5 procesa mensajes de cualquier longitud (longitud variable) y procesa bloques uniformes de 512 bits a la vez, hasta concluir con el mensaje total a fin de entregar a la salida un bloque \"resumen\" de 128 bits (longitud fija). El procesamiento consta de cinco pasos:</html>");
        IntroMD5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1000, -1));

        jLabel15.setText("<html><strong>Paso 1</strong>: Adición de bits<br><br> <strong>Paso 2</strong>: Adición de longitud del mensaje<br><br> <strong>Paso 3</strong>: Inicialización del buffer<br><br> <strong>Paso 4</strong>: Procesamiento del mensaje en bloques de 16 palabras<br><br><strong>Paso 5</strong>: Obtención del hash de salida<br><br></html>");
        jLabel15.setDoubleBuffered(true);
        IntroMD5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 420, 190));

        jTabbedPane1.addTab("Introducción", IntroMD5);

        panelPaso1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderPaso3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeaderPaso3.setText("Paso 1: Adición de bits y de longitud");
        panelPaso1.add(lblHeaderPaso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton1.setText("Siguiente");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelPaso1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, -1, -1));

        jLabel2.setText("<html> A modo de ejemplo, supongamos que queremos encriptar un mensaje menor a 512 caracteres. Si el mensaje fuera más largo, el algoritmo parte el mensaje en bloques de 512 y trabaja por bloques</html>");
        panelPaso1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1000, 40));

        textMensaje.setText("TOP SECRET MESSAGE");
        textMensaje.setToolTipText("");
        textMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMensajeActionPerformed(evt);
            }
        });
        panelPaso1.add(textMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 220, -1));

        jLabel66.setText("<html>Introduzca aqui el mensaje en representación binaria teniendo <br/>en cuenta la adicion de bits y de longitudad para formar un <br/> bloque de 512:</html>");
        panelPaso1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelPaso1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 490, 170));

        jLabel80.setText("Introduzca un mensaje:");
        panelPaso1.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jButton6.setText("Validar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelPaso1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 80, -1));

        jButton7.setText("Mostrar");
        panelPaso1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 80, -1));

        jTabbedPane1.addTab("Paso 1 de 5", panelPaso1);

        panelPaso2.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Paso 2: Ronda 1");
        panelPaso2.add(jLabel32);
        jLabel32.setBounds(21, 12, 145, 22);

        jButton2.setText("Siguiente");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        panelPaso2.add(jButton2);
        jButton2.setBounds(710, 450, 100, 23);

        jTabbedPane1.addTab("Paso 2 de 5", panelPaso2);

        panelPaso3.setPreferredSize(new java.awt.Dimension(640, 860));
        panelPaso3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Paso 3: Ronda 2");
        panelPaso3.add(jLabel14);
        jLabel14.setBounds(30, 12, 145, 22);

        jButton4.setText("Siguiente");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        panelPaso3.add(jButton4);
        jButton4.setBounds(850, 390, 120, 30);

        jTabbedPane1.addTab("Paso 3 de 5", panelPaso3);

        panelPaso4i.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel79.setText("Paso 4: Ronda 3");
        panelPaso4i.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/md5/funcionesMd5.jpg"))); // NOI18N
        panelPaso4i.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 360, 160));

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel82.setText("Operaciones no lineales usadas por cada ronda:");
        panelPaso4i.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jButton13.setText("Siguiente");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton13MousePressed(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panelPaso4i.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 520, -1, -1));

        jTabbedPane1.addTab("Paso 4i de 5", panelPaso4i);

        panelPaso4ii.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Paso 4: Ronda 4");
        panelPaso4ii.add(jLabel26);
        jLabel26.setBounds(20, 10, 145, 22);
        panelPaso4ii.add(sumaFinal);
        sumaFinal.setBounds(660, 500, 440, 20);
        panelPaso4ii.add(ronda1fila2);
        ronda1fila2.setBounds(670, 150, 550, 15);

        jButton5.setText("Siguiente");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelPaso4ii.add(jButton5);
        jButton5.setBounds(1100, 520, 110, 30);
        panelPaso4ii.add(ronda1fila1);
        ronda1fila1.setBounds(670, 130, 520, 15);
        panelPaso4ii.add(ronda1fila4);
        ronda1fila4.setBounds(670, 190, 550, 15);
        panelPaso4ii.add(ronda1fila3);
        ronda1fila3.setBounds(670, 170, 550, 15);
        panelPaso4ii.add(ronda1fila5);
        ronda1fila5.setBounds(670, 220, 550, 15);
        panelPaso4ii.add(ronda1fila6);
        ronda1fila6.setBounds(670, 280, 550, 15);
        panelPaso4ii.add(ronda1fila7);
        ronda1fila7.setBounds(670, 260, 550, 15);
        panelPaso4ii.add(ronda1fila8);
        ronda1fila8.setBounds(670, 240, 550, 15);
        panelPaso4ii.add(ronda1fila9);
        ronda1fila9.setBounds(670, 330, 550, 15);
        panelPaso4ii.add(ronda1fila10);
        ronda1fila10.setBounds(670, 310, 550, 15);
        panelPaso4ii.add(ronda1fila11);
        ronda1fila11.setBounds(670, 350, 550, 15);
        panelPaso4ii.add(ronda1fila12);
        ronda1fila12.setBounds(670, 370, 550, 15);
        panelPaso4ii.add(ronda1fila13);
        ronda1fila13.setBounds(670, 430, 550, 15);
        panelPaso4ii.add(ronda1fila14);
        ronda1fila14.setBounds(670, 410, 550, 15);
        panelPaso4ii.add(ronda1fila15);
        ronda1fila15.setBounds(670, 450, 550, 15);
        panelPaso4ii.add(ronda1fila16);
        ronda1fila16.setBounds(670, 470, 550, 15);
        panelPaso4ii.add(valoresIniciales);
        valoresIniciales.setBounds(670, 100, 550, 15);

        jTabbedPane1.addTab("Paso 4ii de 5", panelPaso4ii);

        panelPaso5.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Paso 5: Salida: message digest o resumen del mensaje");
        panelPaso5.add(jLabel25);
        jLabel25.setBounds(12, 12, 491, 22);
        panelPaso5.add(hashSalida);
        hashSalida.setBounds(270, 310, 0, 0);

        jTabbedPane1.addTab("Paso 5 de 5", panelPaso5);

        add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 50, 1250, 600);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MD5");
        add(jLabel1);
        jLabel1.setBounds(480, 10, 41, 22);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        jTabbedPane1.setEnabledAt(3, true);
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton2MousePressed

    private void textMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMensajeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MousePressed
       jTabbedPane1.setEnabledAt(5, true);
       jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jButton13MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTabbedPane1.setEnabledAt(6, true);
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_jButton5ActionPerformed
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
            char chrTestData[] = new char[64];
            chrTestData = textMensaje.getText().toCharArray();
            md5.update(chrTestData, chrTestData.length);
            md5.md5final();
            hashSalida.setText("hola");//"<html><div style=\"background-color: white;\"><b>"+"hola"+md5.toHexString().toString()+"</b></html>");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    int pasos= 0; int limite = 0;
    MD5 md5 = new MD5();
    int iteracionRonda1 = 0;    int iteracionRonda2 = 0;    int iteracionRonda3 = 0;    int iteracionRonda4 = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IntroMD5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel hashSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblHeaderPaso3;
    private javax.swing.JPanel panelPaso1;
    private javax.swing.JPanel panelPaso2;
    private javax.swing.JPanel panelPaso3;
    private javax.swing.JPanel panelPaso4i;
    private javax.swing.JPanel panelPaso4ii;
    private javax.swing.JPanel panelPaso5;
    private javax.swing.JLabel ronda1fila1;
    private javax.swing.JLabel ronda1fila10;
    private javax.swing.JLabel ronda1fila11;
    private javax.swing.JLabel ronda1fila12;
    private javax.swing.JLabel ronda1fila13;
    private javax.swing.JLabel ronda1fila14;
    private javax.swing.JLabel ronda1fila15;
    private javax.swing.JLabel ronda1fila16;
    private javax.swing.JLabel ronda1fila2;
    private javax.swing.JLabel ronda1fila3;
    private javax.swing.JLabel ronda1fila4;
    private javax.swing.JLabel ronda1fila5;
    private javax.swing.JLabel ronda1fila6;
    private javax.swing.JLabel ronda1fila7;
    private javax.swing.JLabel ronda1fila8;
    private javax.swing.JLabel ronda1fila9;
    private javax.swing.JLabel sumaFinal;
    private javax.swing.JTextField textMensaje;
    private javax.swing.JLabel valoresIniciales;
    // End of variables declaration//GEN-END:variables

}
